### ISSUE TITLE
This is the overridden method ('load').   ImageStreamCompleter load(T key, DecoderCallback decode);                        ^ Exception: Errors during snapshot creation: null

### ISSUE THREAD

**Issue by mana-ai** [fluttercandies/extended_image_library#12]
```
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:692:24: Context: This is the
overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
/Users/jintian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_fi
le_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than
those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:624:24: Context: This is the
overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
/Users/jintian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_as
set_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional
arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the
overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/Users/jintian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_as
set_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional
arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the
overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/Users/jintian/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_ne
twork_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments
than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
/Users/jintian/development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the
overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:230:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure>
(package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:224:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:400:28)
#9      buildWithAssemble (package:flutter_tools/src/bundle.dart:125:48)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     buildWithAssemble (package:flutter_tools/src/bundle.dart:99:31)
#12     BundleBuilder.build (package:flutter_tools/src/bundle.dart:75:11)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     BundleBuilder.build (package:flutter_tools/src/bundle.dart:52:21)
#15     IOSSimulator._sideloadUpdatedAssetsForInstalledApplicationBundle
(package:flutter_tools/src/ios/simulators.dart:453:28)
#16     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:420:11)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#18     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:419:46)
#19     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:352:15)
#20     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#21     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:32)
#22     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:380:54)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#32     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


Failed to build bundle.
Error launching application on iPhone Xʀ.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.188, on Mac OS X 10.14.6 18G71a, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (not installed)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/80  the same,solution at the end
