### ISSUE TITLE
[Bug report] Cannot build for web after updating to 3.5.0

### ISSUE THREAD

**Issue by masewo** [fluttercandies/extended_image_library#55]
### Version

3.5.0

### Platforms

Web

### Device Model

Chrome

### flutter info

```sh
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.19045.2965], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.23)
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

### How to reproduce?

Build project with extended_image library 3.5.0 for web platform.

### Logs

```sh
/D:/Dart/Pub/Cache/hosted/pub.dev/extended_image_library-3.5.0/lib/src/network/extended_network_image_provider.dart:6:8: Error: Error when reading '/D:/Dart/Pub/Cache/hosted/pub.dev/extended_image_library-3.5.0/lib/src/network/_network_image_web.dart': Das System kann die angegebene Datei nicht finden.

import 'network_image_io.dart' if (dart.library.html) '_network_image_web.dart'
       ^
/D:/Dart/Pub/Cache/hosted/pub.dev/extended_image_library-3.5.0/lib/src/network/extended_network_image_provider.dart:30:8: Error: Couldn't find constructor 'network_image.ExtendedNetworkImageProvider'.
  }) = network_image.ExtendedNetworkImageProvider;
       ^
/D:/Dart/Pub/Cache/hosted/pub.dev/extended_image_library-3.5.0/lib/src/network/extended_network_image_provider.dart:30:8: Error: Redirection constructor target not found: 'network_image.ExtendedNetworkImageProvider'
  }) = network_image.ExtendedNetworkImageProvider;
       ^
/D:/Dart/Pub/Cache/hosted/pub.dev/extended_image_library-3.5.0/lib/src/network/extended_network_image_provider.dart:73:21: Error: Undefined name 'ExtendedNetworkImageProvider'.
      network_image.ExtendedNetworkImageProvider.httpClient;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
Null check operator used on a null value
#0      ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4174:40)
#1      ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3909:17)
#2      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2593:25)
#3      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3943:18)
#4      ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3905:17)
#5      ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3718:11)
#6      ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2156:25)
#7      ProgramCompiler._withMethodDeclarationContext (package:dev_compiler/src/kernel/compiler.dart:3969:24)
#8      ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:2155:12)
#9      ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2096:23)
#10     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:818:21)
#11     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:732:25)
#12     List.forEach (dart:core-patch/growable_array.dart:416:8)
#13     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:670:23)
#14     List.forEach (dart:core-patch/growable_array.dart)
#15     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:479:15)
#16     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:217:33)
#17     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:778:46)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:641:9)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
<asynchronous suspension>
Failed to compile application.
Finished with error: the Dart compiler exited unexpectedly.
```

**Comment by zmtzawqlp** [comment]
The same issue https://github.com/fluttercandies/extended_image_library/issues/53
